application: ben-lu
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /(.*\.(gif|png|jpg|ico|js|css))
  static_files: static/\1
  upload: (.*\.(gif|png|jpg|ico|js|css))

- url: /admin
  script: admin.app
  login: admin
  auth_fail_action: redirect
  
- url: /shell(\.do)?
  script: shell.app
  login: admin
  auth_fail_action: redirect
  
- url: /(ip)?logger
  script: main.app
  login: admin
  auth_fail_action: redirect
  
- url: /.*
  script: main.app
  
- url: /_ah/login_required
  script: do_openid_login.app
  
libraries:
- name: jinja2
  version: latest
#- name: django
#  version: latest
#- name: lxml
#  version: latest
#- name: PIL
#  version: latest
#- name: pycrypto
#  version: latest

builtins:
- appstats: on